#define KEY_ESC         1
#define KEY_UP          72
#define KEY_DOWN        80
#define KEY_LEPHT       75
#define KEY_RIGHT       77

#define KEY_0           11
#define KEY_1           2
#define KEY_2           3
#define KEY_3           4
#define KEY_4           5
#define KEY_5           6
#define KEY_6           7
#define KEY_7           8
#define KEY_8           9
#define KEY_9           10

#define KEY_A           30
#define KEY_B           48
#define KEY_C           46
#define KEY_D           32
#define KEY_E           18
#define KEY_PH          33


#define KEY_G           34
#define KEY_J           36
#define KEY_L           38
#define KEY_N           49
#define KEY_P           25
#define KEY_R           19
#define KEY_S           31
#define KEY_Y           21



#define KEY_ENTER       28

#define KEY_APOS        40
#define KEY_BSLASH      43

#define KEY_INS         82
#define KEY_DEL         83

#define KEY_SPACE       0x39
#define KEY_BKSPACE     14

#define KEY_PGUP        73
#define KEY_PGDOWN      81

#define KEY_HOME        71
#define KEY_END         79


#define KEY_TAB         15

#define KEY_CAPSLK      58


#define KEY_JUMP        86

#define KEY_ALT         56
#define KEY_CTRL        29

#define KEY_PLUS        12
#define KEY_NUMPLUS     78
#define KEY_MINUS       53
#define KEY_NUMMINUS    74

#define KEY_NUMSLASH    53
#define KEY_NUMASTERISK 55

#define KEY_COMMA       51
#define KEY_PERIOD      52


#define KEY_PH1         59
#define KEY_PH2         60
#define KEY_PH3         61
#define KEY_PH4         62
#define KEY_PH5         63
#define KEY_PH6         64
#define KEY_PH7         65
#define KEY_PH8         66
#define KEY_PH9         67
#define KEY_PH10        68
#define KEY_PH11        87
#define KEY_PH12        134

#define KEY_UPLEPHT     41


#define KEY_LEFTSHIFT   0x2A
#define KEY_RIGHTSHIFT  0x36
