#ifndef _TYPEDEFS_H_INCLUDED
        #define _TYPEDEFS_H_INCLUDED

        #ifndef NULL
                #define NULL    0
        #endif

        typedef unsigned char   uBYTE;
        typedef   signed char   sBYTE;    
        typedef uBYTE            BYTE;
        typedef unsigned short  uWORD;   
        typedef   signed short  sWORD;   
        typedef uWORD            WORD;
        typedef unsigned long   uDWORD;  
        typedef signed long     sDWORD;    
        typedef uDWORD           DWORD;  

#endif  // _TYPEDEFS_H_INCLUDED
